name: Enforce PR label
description: Enforces that a PR has at least one required label

runs:
  using: composite
  steps:
    - uses: yogevbd/enforce-label-action@a3c219da6b8fa73f6ba62b68ff09c469b3a1c024 # 2.2.2
      with:
        REQUIRED_LABELS_ANY: "bug,enhancement,dependencies,maintenance,documentation"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label: bug,enhancement,dependencies,maintenance,documentation"
        BANNED_LABELS: ""
