name: Build & publish PyPI package
description: Builds and inspects the package, then publishes to PyPI

inputs:
  repository-url:
    required: false
    default: ""
    description: "PyPI repository URL (omit for real PyPI, set for Test PyPI)"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false

    - uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516 # v2.14.0

    - name: Upload package to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
      with:
        repository-url: ${{ inputs.repository-url }}
