name: Test SDist
description: Downloads the sdist artifact, unpacks it, and runs the test suite

inputs:
  setup:
    required: false
    default: "poetry sync --only main,tests"
  command:
    required: false
    default: "poetry run pytest -v"
    description: "Command to run the test suite from within the unpacked sdist directory"

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist

    - name: Run setup
      shell: bash
      env:
        COMMAND: ${{ inputs.setup }}
      run: |
        $COMMAND

    - name: Unpack sdist
      shell: bash
      run: |
        mkdir sdist_unpack
        tar xf dist/*.tar.gz --strip-components=1 -C sdist_unpack

    - name: Run tests
      shell: bash
      working-directory: sdist_unpack
      env:
        COMMAND: ${{ inputs.command }}
      run: |
        $COMMAND
