name: Test SDist
description: Downloads the sdist artifact, unpacks it, and runs the test suite

inputs:
  command:
    required: false
    default: "pytest -v"
    description: "Command to run the test suite from within the unpacked sdist directory"

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5

    - name: Install Poetry
      shell: bash
      run: pipx install "poetry>=2.3,<3"

    - name: Install test dependencies
      shell: bash
      run: |
        poetry install --sync --with test
        poetry run pip install -q --no-deps -e ./metakernel_python/
        poetry run python -m metakernel_python install --sys-prefix

    - uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist

    - name: Unpack sdist
      shell: bash
      run: |
        mkdir sdist_unpack
        tar xf dist/*.tar.gz --strip-components=1 -C sdist_unpack

    - name: Run tests
      shell: bash
      working-directory: sdist_unpack
      env:
        COMMAND: ${{ inputs.command }}
      run: |
        VENV=$(cd .. && poetry env info --path)
        PATH="$VENV/bin:$PATH" $COMMAND
