#!/bin/bash
set -e

# Install metakernel with all extras and local kernels
pip install --no-deps . ./metakernel_python ./metakernel_echo

# Enable ipyparallel server extension
jupyter server extension enable ipyparallel --sys-prefix

# Clean up pip cache
pip cache purge

# Clean up conda cache
conda clean --all --yes
