name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 1.0.0, patch, minor, rc, dev)"
        required: true
        type: string
      dry_run:
        description: "Dry run (deletes draft release, does not push changes, does not publish to PyPI"
        required: false
        type: boolean
        default: false
  schedule:
    - cron: "0 9 * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/release
        with:
          version: ${{ github.event_name == 'schedule' && '10.10.10.10' || inputs.version }}
          dry_run: ${{ github.event_name == 'schedule' && 'true' || inputs.dry_run }}
          app_id: ${{ vars.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          ref: ${{ github.ref_name }}

  publish:
    needs: [release]
    runs-on: ubuntu-latest
    environment: release
    permissions:
        id-token: write
        attestations: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516 # v2.14.0

    - name: Upload package to Test PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
      with:
        repository-url: https://test.pypi.org/legacy/

    - name: Upload package to PyPI
      if: ${{ inputs.dry_run != 'true' }}
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
      with:
        repository-url: https://test.pypi.org/legacy/
